[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "vector-hunter"
version = "0.1.0"
description = ""
authors = [
    { name = "tinuviel60" }
]

dependencies = [
    "pygame>=2.5",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "black",
]

[tool.setuptools]
package-dir = { "" = "sources" }

[tool.setuptools.packages.find]
where = ["sources"]
