"""
Vector Hunt - API summary.

Auto-generated by scripts/generate_api_summary.py
Version: 0.1.1
"""

# Engine
# components
from .engine.components import (
    Component,
    PhysicBodyComponent,
    RenderComponent,
)

# core
from .engine.core import (
    CAN_COLLIDE,
    CAN_DESTROY,
    CAN_PICKUP,
    Geometry,
    Position2D,
    Rotation,
    Tag,
    TagSystem,
    Transform,
    Vector2D,
    hex_to_rgb,
)

# input
from .engine.input import (
    ActionState,
    ActionType,
    ContextManager,
    GameContext,
    InputAction,
    InputSystem,
    InputTracker,
    action_from_config,
)

# objects
from .engine.objects import (
    GameObject,
    GameObjectFactory,
)

# physics
from .engine.physics import (
    ColliderSystem,
    CollisionTracker,
    CombineMode,
    ExternalForcesSystem,
    PhysicMaterial,
)

# rendering
from .engine.rendering import (
    Renderer,
)

# resources
from .engine.resources import (
    Paths,
)

# utils
from .engine.utils import (
    load_all_components,
)

# worlds
from .engine.worlds import (
    World,
)

# Game
# root
from .game import (
    Game,
)

__version__ = "0.1.1"

__all__ = [
    # Engine
    # components
    "Component",
    "PhysicBodyComponent",
    "RenderComponent",
    # core
    "CAN_COLLIDE",
    "CAN_DESTROY",
    "CAN_PICKUP",
    "Geometry",
    "Position2D",
    "Rotation",
    "Tag",
    "TagSystem",
    "Transform",
    "Vector2D",
    "hex_to_rgb",
    # input
    "ActionState",
    "ActionType",
    "ContextManager",
    "GameContext",
    "InputAction",
    "InputSystem",
    "InputTracker",
    "action_from_config",
    # objects
    "GameObject",
    "GameObjectFactory",
    # physics
    "ColliderSystem",
    "CollisionTracker",
    "CombineMode",
    "ExternalForcesSystem",
    "PhysicMaterial",
    # rendering
    "Renderer",
    # resources
    "Paths",
    # utils
    "load_all_components",
    # worlds
    "World",
    # Game
    # root
    "Game",
]
