"""
Script to scan a directory for Python modules and generate an API summary file.
Usage:
    python generate_api_summary.py <target_dir> [--version VERSION]
The summary will be written to 'api_modules.py' next to __init__.py in the target directory.
"""

import os
import ast
from collections import defaultdict

TEMPLATE = '''"""
Vector Hunt - API summary.

Auto-generated by scripts/generate_api_summary.py
Version: {version}
"""

{imports}

__version__ = "{version}"

__all__ = [
{entries}
]
'''

def _extract_all_names(file_path: str) -> list[str]:
    with open(file_path, "r", encoding="utf-8") as handle:
        tree = ast.parse(handle.read(), filename=file_path)
    for node in tree.body:
        if isinstance(node, ast.Assign):
            for target in node.targets:
                if isinstance(target, ast.Name) and target.id in ("__all__", "__ALL__"):
                    if isinstance(node.value, (ast.List, ast.Tuple)):
                        values = []
                        for elt in node.value.elts:
                            if isinstance(elt, ast.Constant) and isinstance(
                                elt.value, str
                            ):
                                values.append(elt.value)
                        return values
    return []

def _group_key(package_path: str) -> tuple[str, str, str | None]:
    if package_path == "engine":
        return ("Engine", "root", None)
    if package_path.startswith("engine."):
        parts = package_path.split(".")
        section = parts[1] if len(parts) > 1 else "engine"
        subsection = parts[2] if len(parts) > 2 else None
        return ("Engine", section, subsection)
    if package_path == "game":
        return ("Game", "root", None)
    if package_path.startswith("game."):
        parts = package_path.split(".")
        section = parts[1] if len(parts) > 1 else "game"
        subsection = parts[2] if len(parts) > 2 else None
        return ("Game", section, subsection)
    return ("Other", "other", None)


def _collect_package_exports(target_dir: str) -> dict[str, list[str]]:
    package_exports = {}
    for root, dirs, files in os.walk(target_dir):
        if "__init__.py" not in files:
            continue
        rel_dir = os.path.relpath(root, target_dir)
        if rel_dir == ".":
            continue
        package_path = rel_dir.replace(os.sep, ".")
        if not (package_path.startswith("engine") or package_path.startswith("game")):
            continue
        if package_path == "engine":
            continue
        parts = package_path.split(".")
        if package_path.startswith("engine.") and len(parts) > 2:
            continue
        if package_path.startswith("game.") and len(parts) > 1:
            continue
        init_path = os.path.join(root, "__init__.py")
        exports = _extract_all_names(init_path)
        if exports:
            package_exports[package_path] = exports
    return package_exports


def _format_import_block(package: str, names: list[str]) -> list[str]:
    names_sorted = sorted(set(names))
    if not names_sorted:
        return []
    lines = [f"from .{package} import ("]
    for name in names_sorted:
        lines.append(f"    {name},")
    lines.append(")")
    return lines


def generate_imports_and_entries(target_dir: str) -> tuple[str, str]:
    package_exports = _collect_package_exports(target_dir)
    grouped = defaultdict(lambda: defaultdict(lambda: defaultdict(list)))
    for package_path, public_names in package_exports.items():
        group, section, subsection = _group_key(package_path)
        grouped[group][section][subsection].append((package_path, public_names))

    import_lines = []
    all_entries = []
    seen = set()
    for group_name in ("Engine", "Game"):
        sections = grouped.get(group_name)
        if not sections:
            continue
        import_lines.append(f"# {group_name}")
        all_entries.append(f"    # {group_name}")
        for section in sorted(sections):
            import_lines.append(f"# {section}")
            all_entries.append(f"    # {section}")
            subsections = sections[section]
            for subsection in sorted(subsections, key=lambda x: (x is None, x)):
                if subsection is not None:
                    import_lines.append(f"# {subsection}")
                    all_entries.append(f"    # {subsection}")
                for package_path, public_names in sorted(subsections[subsection]):
                    import_lines.extend(_format_import_block(package_path, public_names))
                    for name in sorted(public_names):
                        if name in seen:
                            continue
                        seen.add(name)
                        all_entries.append(f'    "{name}",')
            import_lines.append("")
    if import_lines and not import_lines[-1]:
        import_lines.pop()
    return ("\n".join(import_lines), "\n".join(all_entries))

def main():
    print("Generate API summary for Python modules.")
    
    #Target directory to scan (e.g., sources/vect_hunt)
    target_dir = os.path.abspath(
        os.path.join(os.path.dirname(__file__), '..', 'sources', 'vect_hunt')
    )

    # Version number for the summary file (aligned with package __init__).
    version = "0.1.1"

    package_exports = _collect_package_exports(target_dir)
    imports, entries = generate_imports_and_entries(target_dir)
    content = TEMPLATE.format(version=version, imports=imports, entries=entries)

    api_path = os.path.join(target_dir, 'api_modules.py')
    with open(api_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(
        f"API summary written to {api_path} ({len(package_exports)} packages found)"
    )

if __name__ == '__main__':
    main()
